
name: GitHub Actions

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  stylecheck:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Style
        run: |
          pip install -r requirements_style.txt --disable-pip-version-check
          make
      - name: flake8
        if: always()
        run: |
          make flake8